const path = require('path');
const fs = require('fs');
const os = require('os');
const express = require('express');
const bodyParser = require('body-parser');

const server = express();
server.use(bodyParser.json());
server.use(bodyParser.urlencoded({  extended: true }));
server.use('/', express.static(path.join(__dirname, 'public')));
server.use('/save', (req, res) => {

  console.log('req.body', JSON.stringify(req.body));
  const json = JSON.stringify(req.body, null, 2);
  const string_to_write = `/**
 * WARNING: Edits to this file will be overwritten! It is generated by server.js.
 */
import { LevelData } from './level';

export const allLevels: Record<string, LevelData> = ${json};
`;

  console.log(string_to_write);
  fs.writeFileSync('src/level-data.ts', string_to_write, 'utf8');
  res.send(JSON.stringify('ok'));
});

const PORT = 8000;
const HOST = process.env.HOST || 'localhost';

/** IPv4 addresses this machine can be reached at from the network. */
function lanAddresses() {
  return Object.values(os.networkInterfaces())
    .flat()
    .filter(iface => iface && iface.family === 'IPv4' && !iface.internal)
    .map(iface => iface.address);
}

server.listen(PORT, HOST, () => {
  console.log(`listening on http://${HOST}:${PORT}...`);
  if (HOST === '0.0.0.0') {
    for (const address of lanAddresses()) {
      console.log(`  reachable at http://${address}:${PORT}`);
    }
  }
});
