/**
 * WARNING: Edits to this file will be overwritten! It is generated by server.js.
 */
import { LevelData } from './level';

export const allLevels: Record<string, LevelData> = {
  "start": {
    "initOverlay": {
      "tiles": {
        "0,1": {
          "t": "static",
          "tile": {
            "t": "up_box"
          }
        },
        "-1,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-3,0": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-3,-1": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "-3,-2": {
          "t": "static",
          "tile": {
            "t": "save_point"
          }
        },
        "-4,3": {
          "t": "static",
          "tile": {
            "t": "up_box"
          }
        },
        "-1,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-5,1": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "-6,1": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-5,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-5,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-3,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-3,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-3,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-2,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-8,2": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-6,2": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "0,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-2,-1": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "-1,-1": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "1,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "3,2": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "6,2": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "left"
          }
        },
        "7,2": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "5,2": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "9,2": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "11,2": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "13,2": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "15,2": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "17,2": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "-7,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-9,6": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-8,3": {
          "t": "static",
          "tile": {
            "t": "grip_wall"
          }
        },
        "-8,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-8,6": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "3,4": {
          "t": "static",
          "tile": {
            "t": "stone"
          }
        },
        "-8,10": {
          "t": "static",
          "tile": {
            "t": "up_box"
          }
        },
        "-9,11": {
          "t": "static",
          "tile": {
            "t": "up_box"
          }
        },
        "-5,0": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-16,10": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-17,9": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-17,10": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "-18,19": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-17,19": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-16,19": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-18,18": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-15,21": {
          "t": "static",
          "tile": {
            "t": "up_box"
          }
        },
        "-7,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-6,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-6,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-5,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-3,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-4,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-2,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-2,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "0,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "0,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-1,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-1,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "3,3": {
          "t": "static",
          "tile": {
            "t": "button_off"
          }
        },
        "-2,0": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-2,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-1,0": {
          "t": "static",
          "tile": {
            "t": "button_on"
          }
        },
        "-12,3": {
          "t": "static",
          "tile": {
            "t": "up_box"
          }
        },
        "-11,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-12,-1": {
          "t": "static",
          "tile": {
            "t": "up_box"
          }
        },
        "-11,-1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-11,0": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-11,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-7,6": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-6,6": {
          "t": "static",
          "tile": {
            "t": "stone"
          }
        },
        "-5,6": {
          "t": "static",
          "tile": {
            "t": "stone"
          }
        },
        "-4,6": {
          "t": "static",
          "tile": {
            "t": "stone"
          }
        },
        "-2,6": {
          "t": "static",
          "tile": {
            "t": "stone"
          }
        },
        "-3,6": {
          "t": "static",
          "tile": {
            "t": "stone"
          }
        },
        "-1,6": {
          "t": "static",
          "tile": {
            "t": "stone"
          }
        },
        "0,6": {
          "t": "static",
          "tile": {
            "t": "stone"
          }
        },
        "1,6": {
          "t": "static",
          "tile": {
            "t": "stone"
          }
        },
        "2,6": {
          "t": "static",
          "tile": {
            "t": "up_box"
          }
        },
        "3,6": {
          "t": "static",
          "tile": {
            "t": "stone"
          }
        },
        "3,5": {
          "t": "static",
          "tile": {
            "t": "stone"
          }
        },
        "-12,2": {
          "t": "static",
          "tile": {
            "t": "item",
            "item": "teal_fruit"
          }
        },
        "-10,3": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "right"
          }
        },
        "1,-2": {
          "t": "static",
          "tile": {
            "t": "grip_wall"
          }
        },
        "17,5": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "16,5": {
          "t": "static",
          "tile": {
            "t": "up_box"
          }
        },
        "15,5": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "18,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "19,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "20,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "21,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "22,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "23,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "18,0": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "19,0": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "20,0": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "21,0": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "22,0": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "23,0": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "18,1": {
          "t": "static",
          "tile": {
            "t": "coin_wall"
          }
        },
        "19,1": {
          "t": "static",
          "tile": {
            "t": "coin_wall"
          }
        },
        "20,1": {
          "t": "static",
          "tile": {
            "t": "coin_wall"
          }
        },
        "21,1": {
          "t": "static",
          "tile": {
            "t": "coin_wall"
          }
        },
        "22,1": {
          "t": "static",
          "tile": {
            "t": "coin_wall"
          }
        },
        "23,1": {
          "t": "static",
          "tile": {
            "t": "coin_wall"
          }
        },
        "23,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "23,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "23,5": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "24,5": {
          "t": "static",
          "tile": {
            "t": "up_box"
          }
        },
        "25,5": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "26,5": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "27,5": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "28,5": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "28,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "28,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "28,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "28,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "28,0": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "28,-1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "28,-2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "28,-3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "27,-3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "25,-3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "24,-3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "23,-3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "23,-1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "23,-2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "26,-3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "27,4": {
          "t": "static",
          "tile": {
            "t": "item",
            "item": "teal_fruit"
          }
        },
        "0,5": {
          "t": "static",
          "tile": {
            "t": "item",
            "item": "coin"
          }
        },
        "-1,5": {
          "t": "static",
          "tile": {
            "t": "item",
            "item": "coin"
          }
        },
        "-2,5": {
          "t": "static",
          "tile": {
            "t": "item",
            "item": "coin"
          }
        },
        "-3,5": {
          "t": "static",
          "tile": {
            "t": "item",
            "item": "coin"
          }
        },
        "-4,5": {
          "t": "static",
          "tile": {
            "t": "item",
            "item": "coin"
          }
        },
        "-5,5": {
          "t": "static",
          "tile": {
            "t": "item",
            "item": "coin"
          }
        },
        "4,2": {
          "t": "timed",
          "phase": 0,
          "off_for": 5,
          "on_for": 1
        },
        "4,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "5,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "6,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "8,4": {
          "t": "static",
          "tile": {
            "t": "up_box"
          }
        },
        "7,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "4,0": {
          "t": "static",
          "tile": {
            "t": "button_off"
          }
        },
        "3,0": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "down"
          }
        },
        "5,0": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "down"
          }
        },
        "3,-1": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "4,-1": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "5,-1": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "6,-1": {
          "t": "timed",
          "phase": 0,
          "off_for": 3,
          "on_for": 1
        },
        "7,-1": {
          "t": "timed",
          "phase": 1,
          "off_for": 3,
          "on_for": 1
        },
        "8,-1": {
          "t": "timed",
          "phase": 2,
          "off_for": 3,
          "on_for": 1
        },
        "9,-1": {
          "t": "timed",
          "phase": 3,
          "off_for": 3,
          "on_for": 1
        },
        "11,-1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "12,-1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "12,-2": {
          "t": "static",
          "tile": {
            "t": "item",
            "item": "teal_fruit"
          }
        },
        "4,-5": {
          "t": "buttoned",
          "button_source": {
            "x": -1,
            "y": 0
          }
        },
        "6,-5": {
          "t": "buttoned",
          "button_source": {
            "x": 4,
            "y": 0
          }
        },
        "-13,-3": {
          "t": "bus_block",
          "bus": "red"
        },
        "-15,-5": {
          "t": "static",
          "tile": {
            "t": "grip_wall"
          }
        },
        "-12,-6": {
          "t": "static",
          "tile": {
            "t": "grip_wall"
          }
        },
        "-15,-7": {
          "t": "static",
          "tile": {
            "t": "grip_wall"
          }
        },
        "-13,-9": {
          "t": "static",
          "tile": {
            "t": "grip_wall"
          }
        },
        "-12,-11": {
          "t": "static",
          "tile": {
            "t": "grip_wall"
          }
        },
        "-10,-11": {
          "t": "bus_block",
          "bus": "blue"
        },
        "-8,-11": {
          "t": "bus_block",
          "bus": "blue"
        },
        "-6,-11": {
          "t": "bus_block",
          "bus": "blue"
        },
        "-14,-11": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-15,-11": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-16,-11": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-17,-12": {
          "t": "bus_button",
          "bus": "blue"
        },
        "-17,-11": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-17,-13": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-16,-13": {
          "t": "bus_block",
          "bus": "red"
        },
        "-15,-13": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-14,-13": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-4,-11": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-3,-12": {
          "t": "bus_button",
          "bus": "red"
        },
        "-3,-11": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-17,-14": {
          "t": "static",
          "tile": {
            "t": "item",
            "item": "coin"
          }
        },
        "-10,-2": {
          "t": "bus_button",
          "bus": "red"
        },
        "-10,-1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-14,-14": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-1,-2": {
          "t": "door",
          "destinationLevel": "boxes"
        },
        "3,-2": {
          "t": "door",
          "destinationLevel": "boxes2"
        },
        "-9,5": {
          "t": "door",
          "destinationLevel": "sideblock"
        },
        "-18,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-17,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-16,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-14,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-13,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-12,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-11,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-10,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-9,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-8,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-7,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-6,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-5,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-4,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-3,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-2,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-1,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "1,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "3,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "2,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "0,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "4,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "5,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "6,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "7,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "8,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "9,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "10,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "11,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "12,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "13,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "14,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "15,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "16,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "17,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "18,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "19,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "20,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "21,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "22,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "23,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "24,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "25,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "26,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "27,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "28,21": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-10,7": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-11,8": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-12,9": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-13,10": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-14,10": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-15,10": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-16,9": {
          "t": "door",
          "destinationLevel": "button-hack"
        }
      }
    },
    "boundRect": {
      "min": {
        "x": -18,
        "y": -14
      },
      "max": {
        "x": 28,
        "y": 21
      }
    }
  },
  "boxes": {
    "initOverlay": {
      "tiles": {
        "0,1": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "-1,1": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "0,2": {
          "t": "static",
          "tile": {
            "t": "coin_wall"
          }
        },
        "1,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "1,3": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "0,3": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "-1,3": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "-7,1": {
          "t": "static",
          "tile": {
            "t": "grip_wall"
          }
        },
        "-10,0": {
          "t": "static",
          "tile": {
            "t": "grip_wall"
          }
        },
        "-7,-1": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "-11,-2": {
          "t": "static",
          "tile": {
            "t": "grip_wall"
          }
        },
        "-5,1": {
          "t": "static",
          "tile": {
            "t": "grip_wall"
          }
        },
        "-2,3": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-3,3": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-4,3": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-5,3": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-6,3": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-7,3": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-8,3": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-9,3": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-10,3": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-11,3": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-11,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-10,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-9,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-8,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-7,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-6,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-5,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-4,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-3,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-2,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-1,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "0,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "1,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-7,-2": {
          "t": "static",
          "tile": {
            "t": "item",
            "item": "coin"
          }
        },
        "2,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "3,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "4,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "5,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "6,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "7,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "2,3": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "3,2": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "4,1": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "4,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "4,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "3,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "5,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "5,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "5,1": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "6,1": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "6,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "7,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "7,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "6,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "7,1": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "4,-1": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "1,0": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "1,-1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "1,-2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "1,-3": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "-9,-3": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "-6,-2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-6,-3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-1,0": {
          "t": "door",
          "destinationLevel": "start"
        }
      }
    },
    "boundRect": {
      "min": {
        "x": -11,
        "y": -4
      },
      "max": {
        "x": 7,
        "y": 4
      }
    }
  },
  "boxes2": {
    "initOverlay": {
      "tiles": {
        "0,1": {
          "t": "static",
          "tile": {
            "t": "up_box"
          }
        },
        "0,0": {
          "t": "door",
          "destinationLevel": "start"
        },
        "5,-3": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "5,-1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "4,-1": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "left"
          }
        },
        "5,-2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "7,-1": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "7,-3": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "down"
          }
        },
        "5,0": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "7,-4": {
          "t": "static",
          "tile": {
            "t": "grip_wall"
          }
        },
        "7,0": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "6,0": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "7,-5": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "8,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "5,-6": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "5,-7": {
          "t": "static",
          "tile": {
            "t": "grip_wall"
          }
        },
        "5,-8": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "9,1": {
          "t": "static",
          "tile": {
            "t": "up_box"
          }
        },
        "9,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "10,-5": {
          "t": "static",
          "tile": {
            "t": "grip_wall"
          }
        },
        "8,-8": {
          "t": "static",
          "tile": {
            "t": "grip_wall"
          }
        },
        "8,-5": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "right"
          }
        },
        "9,-6": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "down"
          }
        },
        "9,-7": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "7,-7": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "left"
          }
        },
        "8,-7": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "6,-9": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "right"
          }
        },
        "5,-9": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "9,-8": {
          "t": "static",
          "tile": {
            "t": "up_box"
          }
        },
        "6,-1": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "7,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "6,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "5,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "4,-12": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "3,-12": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "3,-11": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "3,-10": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "3,-9": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "4,-9": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-2,0": {
          "t": "static",
          "tile": {
            "t": "coin_wall"
          }
        },
        "-1,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-2,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-3,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-4,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-4,0": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-4,-1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-3,-1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-2,-1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-3,0": {
          "t": "static",
          "tile": {
            "t": "item",
            "item": "teal_fruit"
          }
        },
        "3,-13": {
          "t": "static",
          "tile": {
            "t": "item",
            "item": "coin"
          }
        },
        "5,1": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "4,3": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "3,3": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "2,3": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "1,3": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "0,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "0,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "0,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "1,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "2,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "3,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "4,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "5,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "5,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "5,-4": {
          "t": "static",
          "tile": {
            "t": "grip_wall"
          }
        },
        "12,-5": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "11,-3": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "right"
          }
        },
        "11,-6": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "down"
          }
        },
        "11,-7": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "10,-3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "12,-7": {
          "t": "bus_button",
          "bus": "red"
        },
        "13,-5": {
          "t": "bus_block",
          "bus": "red"
        },
        "14,-5": {
          "t": "bus_block",
          "bus": "red"
        },
        "15,-5": {
          "t": "bus_block",
          "bus": "red"
        },
        "16,-5": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "16,-6": {
          "t": "door",
          "destinationLevel": "boxes3"
        },
        "13,-7": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "14,-7": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "15,-7": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "16,-7": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "17,-7": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "17,-6": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "17,-5": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "11,-8": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "12,-8": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "13,-8": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "14,-8": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "15,-8": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "16,-8": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "17,-8": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "1,-7": {
          "t": "static",
          "tile": {
            "t": "stone"
          }
        },
        "2,-5": {
          "t": "static",
          "tile": {
            "t": "stone"
          }
        },
        "1,-11": {
          "t": "static",
          "tile": {
            "t": "stone"
          }
        },
        "11,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        }
      }
    },
    "boundRect": {
      "min": {
        "x": -4,
        "y": -13
      },
      "max": {
        "x": 17,
        "y": 4
      }
    }
  },
  "sideblock": {
    "initOverlay": {
      "tiles": {
        "6,2": {
          "t": "static",
          "tile": {
            "t": "side_breakable"
          }
        },
        "3,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "2,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "1,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "6,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "3,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "4,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "5,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "7,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "8,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "8,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "7,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "10,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "10,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "10,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "10,5": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "6,5": {
          "t": "static",
          "tile": {
            "t": "side_breakable"
          }
        },
        "5,5": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "4,5": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "3,5": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "7,6": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "8,6": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "6,6": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "5,6": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "10,6": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "9,6": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "4,6": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "3,6": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "2,6": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "1,6": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "0,6": {
          "t": "static",
          "tile": {
            "t": "up_box"
          }
        },
        "-1,6": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-1,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-2,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-3,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-4,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-4,5": {
          "t": "static",
          "tile": {
            "t": "item",
            "item": "coin"
          }
        },
        "-4,6": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-3,6": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-2,6": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-3,5": {
          "t": "static",
          "tile": {
            "t": "side_breakable"
          }
        },
        "-5,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-5,5": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-5,6": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "2,5": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "1,5": {
          "t": "bus_block",
          "bus": "red"
        },
        "-5,3": {
          "t": "bus_button",
          "bus": "red"
        },
        "10,-5": {
          "t": "door",
          "destinationLevel": "start"
        },
        "10,-4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "9,-3": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "8,-4": {
          "t": "bus_block",
          "bus": "red"
        },
        "11,-5": {
          "t": "bus_button",
          "bus": "red"
        },
        "11,-4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "11,-6": {
          "t": "static",
          "tile": {
            "t": "box3"
          }
        },
        "8,-3": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "8,-2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "9,-2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "11,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "12,0": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "13,-1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "14,-2": {
          "t": "static",
          "tile": {
            "t": "up_box"
          }
        },
        "11,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "12,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "13,0": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "14,-1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "7,-2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "7,-3": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "13,-2": {
          "t": "static",
          "tile": {
            "t": "coin_wall"
          }
        }
      }
    },
    "boundRect": {
      "min": {
        "x": -5,
        "y": -6
      },
      "max": {
        "x": 14,
        "y": 6
      }
    }
  },
  "boxes3": {
    "initOverlay": {
      "tiles": {
        "2,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "1,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "0,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-1,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-2,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-3,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-3,0": {
          "t": "door",
          "destinationLevel": "boxes2"
        }
      }
    },
    "boundRect": {
      "min": {
        "x": -3,
        "y": 0
      },
      "max": {
        "x": 2,
        "y": 1
      }
    }
  },
  "_test1": {
    "initOverlay": {
      "tiles": {
        "0,1": {
          "t": "static",
          "tile": {
            "t": "up_box"
          }
        }
      }
    },
    "boundRect": {
      "min": {
        "x": -1,
        "y": -1
      },
      "max": {
        "x": 1,
        "y": 2
      }
    }
  },
  "_test2": {
    "initOverlay": {
      "tiles": {
        "0,1": {
          "t": "static",
          "tile": {
            "t": "up_box"
          }
        },
        "0,-1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        }
      }
    },
    "boundRect": {
      "min": {
        "x": -1,
        "y": -2
      },
      "max": {
        "x": 1,
        "y": 2
      }
    }
  },
  "_test3": {
    "initOverlay": {
      "tiles": {
        "0,1": {
          "t": "static",
          "tile": {
            "t": "up_box"
          }
        },
        "-2,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        }
      }
    },
    "boundRect": {
      "min": {
        "x": -3,
        "y": -1
      },
      "max": {
        "x": 1,
        "y": 2
      }
    }
  },
  "_test4": {
    "initOverlay": {
      "tiles": {
        "0,1": {
          "t": "static",
          "tile": {
            "t": "up_box"
          }
        },
        "-1,-2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "0,-3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        }
      }
    },
    "boundRect": {
      "min": {
        "x": -2,
        "y": -4
      },
      "max": {
        "x": 1,
        "y": 2
      }
    }
  },
  "_test5": {
    "initOverlay": {
      "tiles": {
        "0,1": {
          "t": "static",
          "tile": {
            "t": "up_box"
          }
        },
        "0,-4": {
          "t": "static",
          "tile": {
            "t": "fragile_box"
          }
        }
      }
    },
    "boundRect": {
      "min": {
        "x": -1,
        "y": -5
      },
      "max": {
        "x": 1,
        "y": 2
      }
    }
  },
  "_test6": {
    "initOverlay": {
      "tiles": {
        "1,-1": {
          "t": "static",
          "tile": {
            "t": "grip_wall"
          }
        },
        "0,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-2,-2": {
          "t": "static",
          "tile": {
            "t": "grip_wall"
          }
        }
      }
    },
    "boundRect": {
      "min": {
        "x": -2,
        "y": -2
      },
      "max": {
        "x": 1,
        "y": 1
      }
    }
  },
  "_test7": {
    "initOverlay": {
      "tiles": {
        "0,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "2,2": {
          "t": "static",
          "tile": {
            "t": "grip_wall"
          }
        }
      }
    },
    "boundRect": {
      "min": {
        "x": 0,
        "y": -2
      },
      "max": {
        "x": 2,
        "y": 4
      }
    }
  },
  "_test8": {
    "initOverlay": {
      "tiles": {
        "0,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "1,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "1,0": {
          "t": "static",
          "tile": {
            "t": "item",
            "item": "teal_fruit"
          }
        },
        "2,1": {
          "t": "static",
          "tile": {
            "t": "up_box"
          }
        },
        "3,-4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        }
      }
    },
    "boundRect": {
      "min": {
        "x": 0,
        "y": -5
      },
      "max": {
        "x": 3,
        "y": 1
      }
    }
  },
  "_test9": {
    "initOverlay": {
      "tiles": {
        "0,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "2,4": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "2,2": {
          "t": "bus_button",
          "bus": "red"
        },
        "2,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "1,4": {
          "t": "bus_block",
          "bus": "red"
        }
      }
    },
    "boundRect": {
      "min": {
        "x": 0,
        "y": 0
      },
      "max": {
        "x": 2,
        "y": 4
      }
    }
  },
  "button-hack": {
    "initOverlay": {
      "tiles": {
        "0,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-2,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-1,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "3,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "0,0": {
          "t": "door",
          "destinationLevel": "start"
        },
        "3,-1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "6,-2": {
          "t": "bus_button",
          "bus": "red"
        },
        "6,0": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "6,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-3,1": {
          "t": "bus_block",
          "bus": "red"
        },
        "7,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "6,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "5,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "4,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "3,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "4,0": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "right"
          }
        },
        "3,0": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "2,-1": {
          "t": "static",
          "tile": {
            "t": "grip_wall"
          }
        },
        "2,0": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "0,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "1,2": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "1,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "2,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "0,3": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "4,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "5,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "5,0": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-5,3": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-4,3": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-3,3": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-2,3": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-1,3": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        },
        "-6,1": {
          "t": "static",
          "tile": {
            "t": "box"
          }
        },
        "-6,0": {
          "t": "static",
          "tile": {
            "t": "item",
            "item": "coin"
          }
        },
        "-6,3": {
          "t": "static",
          "tile": {
            "t": "spike",
            "direction": "up"
          }
        }
      }
    },
    "boundRect": {
      "min": {
        "x": -6,
        "y": -3
      },
      "max": {
        "x": 7,
        "y": 3
      }
    }
  }
};
